name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
           sudo apt-get install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
           ls
           cd /Driver/uinput
    - name: make
      run: make
    - name: make module
      run: make module
    - name: make distcheck
      run: make clean
