name: Make CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: sudo apt-get install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf swig3.0
    - name: make
      run: |
            cd src/uinput
            make
    - name: make clean
      run: |
            cd src/uinput
            make clean
    - name: test
      run: |
            cd src/uinput
            ./test.sh
